services:
  cometbft-node:
    container_name: cometbft-node${NODE_ID}
    user: ${UID}:${GID}
    image: "cometbft/cometbft:${COMETBFT_VERSION}"
    ports:
      - "${PORT1}-${PORT2}:26656-26657"
    environment:
      - ID=${NODE_ID}
      - LOG=${LOG:-cometbft-node${NODE_ID}.log}
      - CMT_PEX=true
      - CMT_PROXY_APP=tcp://fendermint-node${NODE_ID}:26658
      - CMT_PERSISTENT_PEERS="${CMT_PERSISTENT_PEERS}"
    volumes:
      - $BASE_DIR/node${NODE_ID}/cometbft:/cometbft
    healthcheck:
      test: curl --fail http://localhost:26657 || exit 1
      interval: 8s
      timeout: 10s
      retries: 20
    networks:
      testnet:
        ipv4_address: ${CMT_NODE_ADDR}

  fendermint-node:
    container_name: fendermint-node${NODE_ID}
    user: ${UID}:${GID}
    image: "fendermint:latest"
    environment:
      - FM_DATA_DIR=/data/fendermint/data
      - FM_CHAIN_NAME=$SUBNET_ID
      - LOG_LEVEL=info
    volumes:
      - $BASE_DIR/node${NODE_ID}:/data
    networks:
      testnet:
        ipv4_address: ${FMT_NODE_ADDR}

  ethapi-node:
    container_name: ethapi-node${NODE_ID}
    user: ${UID}:${GID}
    image: "fendermint:latest"
    command: "eth run"
    environment:
      - TENDERMINT_WS_URL=ws://cometbft-node${NODE_ID}:26657/websocket
      - LOG_LEVEL=debug
      - RUST_BACKTRACE=1
    ports:
      - ${PORT3}:8545
    volumes:
      - $BASE_DIR/node${NODE_ID}:/data
    depends_on:
      cometbft-node:
        condition: service_healthy
    networks:
      testnet:
        ipv4_address: ${ETHAPI_NODE_ADDR}

networks:
  testnet:
    name: ${NETWORK_NAME}
    external: true
