[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./out"}]
remappings = [
    "@consensus-shipyard/=node_modules/@consensus-shipyard/"
]
allow_paths = ["../../contracts"]