networks:
  # Network created externally so individual containers can be destroyed without the network being removed.
  ipc:
    external: true
    name: ${IPC_NETWORK}

# Cross mounting volumes: https://github.com/docker/compose/issues/3211
volumes:
  # Volume through which the daemon and the validator will communicate.
  repo_directory: {}

services:

  # Run the daemon, which the `eudico-root-single.sh` script ran in the first tmux window.
  daemon:
    image: eudico:latest
    # The container name could contain the ${IPC_NODE_TYPE} but that would suggest that type and number are unique together,
    # whereas with the current setup the node number is unique on its own. Look at the image to tell what kind we are talking to.
    container_name: ipc-node-${IPC_NODE_NR}-daemon
    # Indicate the type in the host name, makes URLs more intuitive.
    hostname: ${IPC_NODE_TYPE}-${IPC_NODE_NR}
    # Ports don't really need to be exposed as all containers should just talk to each other.
    ports:
      # Lotus port - 1234 hardcoded in subnet-daemon.sh
      - 123${IPC_NODE_NR}:1234
      # libp2p port
      # - 134${IPC_NODE_NR}:1347
    volumes:
      # Volume to be shared with the validator.
      - repo_directory:/var/lib/lotus
      # Modified versions of the infra scripts. Mounted from templates so they can be edited between restarts.
      - ${IPC_PROJECT_ROOT}/testing/e2e/template/${IPC_NODE_TYPE}/scripts:/scripts
    networks:
      - ipc
    environment:
      HOME: /root
      LOTUS_PATH: /var/lib/lotus
    env_file:
      - .env
    entrypoint:
      - /scripts/subnet-daemon.sh
      - ${IPC_SUBNET_ID}

  # Run the validator, which the `eudico-root-single.sh` script ran in the second tmux window.
  validator:
    image: eudico:latest
    # The container name could contain the ${IPC_NODE_TYPE} but that would suggest that type and number are unique together,
    # whereas with the current setup the node number is unique on its own. Look at the image to tell what kind we are talking to.
    container_name: ipc-node-${IPC_NODE_NR}-validator
    volumes:
      # Volume to be shared with the daemon. Has to be the same, a config is not enough.
      - repo_directory:/var/lib/lotus
      # Modified versions of the infra scripts. Mounted from templates so they can be edited between restarts.
      - ${IPC_PROJECT_ROOT}/testing/e2e/template/${IPC_NODE_TYPE}/scripts:/scripts
      # TODO: The key will have to come from a different place for non-root validators.
      - ${IPC_PROJECT_ROOT}/bin/ipc-infra/src/wallet.key:/wallet.key
    networks:
      - ipc
    environment:
      HOME: /root
      LOTUS_PATH: /var/lib/lotus
      DAEMON_HOSTNAME: ${IPC_NODE_TYPE}-${IPC_NODE_NR}
    env_file:
      - .env
    entrypoint:
      - /scripts/validator-entry.sh
    depends_on:
      # The daemon will produce the API token under the shared LOTUS_PATH
      - daemon
