[package]
name = "fil_actor_adm"
description = "ADM actor types and interface"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }

