[package]
name = "ipc-sdk"
description = "IPC common types and utils"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
fil_actors_runtime = { workspace = true, optional = true }
fnv = "1.0.7"
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
integer-encoding = { version = "3.0.3", default-features = false }
lazy_static = { workspace = true }
log = { workspace = true }
cid = { workspace = true }
primitives = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_tuple = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = "1.0.95"
fil_actors_runtime = { workspace = true }

[features]
default = ["fil-actor"]
fil-actor = ["fil_actors_runtime"]