[package]
name = "fendermint_app_options"
description = "Fendermint CLI options"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
num-traits = { workspace = true }
tendermint-rpc = { workspace = true }
tracing = { workspace = true }

cid = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }
ipc-sdk = { workspace = true }
