global:
  scrape_interval: 30s
  evaluation_interval: 25s

# This config for the three-node single machine deploys.
# Change this for production, where prometheus only watches a single node.
scrape_configs:
  - job_name: "prometheus1"
    static_configs:
      - targets: [
        # note the ports are the container internal values since we are using the network domain resolution
        "relayer:9184",
        "validator-0-fendermint:9184",
        "validator-1-fendermint:9184",
        "validator-2-fendermint:9184",
        "validator-0-iroh:9090",
        "validator-1-iroh:9090",
        "validator-2-iroh:9090",
        "prometheus:9090"
      ]
