[package]
name = "ipc_e2e"
description = "IPC end-to-end tests, which rely on an external environment set up and running."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }

fvm_shared = { workspace = true }

ipc-sdk = { workspace = true }
ipc-agent = { path = "../.." }


[dev-dependencies]
tokio = { workspace = true }
log = { workspace = true }
